.TH sos-linux 8
.SH NAME
sos-linux \- create file containing AoE-related information
.SH SYNOPSIS
.nf
.B sos-linux
.fi
.SH DESCRIPTION
The
.I sos-linux
script creates a dated output file in the home directory of the user
running it.
.PP
The filename is printed on the standard output.
.PP
The file contains information about the local system that is likely
to be relevant to its use as an AoE initiator.
.SH "SEE ALSO"
.IR aoe-stat (8),
.IR aoetools (8).
.SH AUTHOR
Ed L. Cashin (ecashin@coraid.com)
